{
 "title": "F5 BIG-IP",
 "description": "Very basic metrics on F5 BIG-IP",
 "tags": [
  "aws",
  "f5",
  "big-ip"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up, job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job='$job'}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SYNC STATUS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_configSyncSucceeded{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK LATENCY R/S",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_r_s{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "{{diskLatency}}"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_cpu{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "systemCPU"
    },
    {
     "expr": "f5_system_tmmCpu{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "tmmCPU"
    }
   ]
  },
  {
   "title": "MEM USAGE",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_memory{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "System RAM"
    },
    {
     "expr": "f5_system_tmmMemory{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "tmm RAM"
    }
   ]
  },
  {
   "title": "DISK USAGE",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_Capacity_Float{job=\"$job\",instance=\"$instance\",diskStorage=\"/\"} * 100",
     "legendFormat": "/"
    },
    {
     "expr": "f5_Capacity_Float{job=\"$job\",instance=\"$instance\",diskStorage=\"/var\"} * 100",
     "legendFormat": "/var"
    },
    {
     "expr": "f5_Capacity_Float{job=\"$job\",instance=\"$instance\",diskStorage=\"/usr\"} * 100",
     "legendFormat": "/usr"
    }
   ]
  },
  {
   "title": "inErrors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_inErrors{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "outErrors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_outErrors{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK LATENCY W/S",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_w_s{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "{{diskLatency}}"
    }
   ]
  },
  {
   "title": "FATAL ALERTS",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_fatalAlerts{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{clientSslProfiles}} {{serverSslProfiles}}"
    }
   ]
  },
  {
   "title": "DISK UTILIZATION %",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5__util{job=\"$job\",instance=\"$instance\"} * 100",
     "legendFormat": "{{diskLatency}}"
    }
   ]
  },
  { "title": "SSL Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "SSL CERTIFICATE STATUS",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "f5_expirationDate{job=\"$job\",instance=\"$instance\"} * 1000",
     "legendFormat": "{{sslCerts}}"
    }
   ]
  },
  {
   "title": "TLS v1.0",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_protocolUses_tlsv1{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{clientSslProfiles}} {{serverSslProfiles}}"
    }
   ]
  },
  {
   "title": "TLS v1.1",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_protocolUses_tlsv1_1{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{clientSslProfiles}} {{serverSslProfiles}}"
    }
   ]
  },
  {
   "title": "TLS v1.2",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_protocolUses_tlsv1_2{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{clientSslProfiles}} {{serverSslProfiles}}"
    }
   ]
  },
  {
   "title": "TLS v1.3",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_protocolUses_tlsv1_3{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{clientSslProfiles}} {{serverSslProfiles}}"
    }
   ]
  },
  {
   "title": "SNI REJECTIONS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_sniRejects{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "{{clientSslProfiles}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CURRENT BITS IN/OUT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "f5_system_throughputPerformance_clientBitsIn_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "In"
    },
    {
     "expr": "f5_system_throughputPerformance_clientBitsOut_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "f5_system_throughputPerformance_clientBitsIn_average{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "In Avg"
    },
    {
     "expr": "f5_system_throughputPerformance_clientBitsOut_average{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Out Avg"
    }
   ]
  },
  {
   "title": "BLADE 0 CONNS",
   "type": "timeseries",
   "description": "System connection performance current and average for Blade zero (0).",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_blade0_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "f5_system_connectionsPerformance_blade0_average{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "CLIENTS",
   "type": "timeseries",
   "description": "System performance client accepts data.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_clientAccepts_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Accepts"
    },
    {
     "expr": "f5_system_connectionsPerformance_clientAccepts_average{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Avg"
    },
    {
     "expr": "f5_system_connectionsPerformance_clientAccepts_max{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "APM Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  { "title": "CURRENT SESSIONS", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 0, "y": 38 } },
  {
   "title": "CLIENT SIDE CONNECTIONS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 3, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_clientside_curConns{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{virtualServers}}"
    }
   ]
  },
  {
   "title": "SERVER SIDE CONNECTIONS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_serverside_curConns{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{pools}}"
    }
   ]
  },
  {
   "title": "TOTAL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_connections_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP REQs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_httpRequests_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "CUR"
    },
    {
     "expr": "f5_system_connectionsPerformance_httpRequests_average{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "HTTPS REQs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_activeSslServerConnections_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "CUR"
    },
    {
     "expr": "f5_system_connectionsPerformance_activeSslServerConnections_average{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "AVG"
    }
   ]
  },
  { "title": "TMM USAGE", "type": "text", "gridPos": { "h": 1, "w": 3, "x": 0, "y": 48 } },
  {
   "title": "TRUNKS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 3, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "f5_system_throughputPerformance_inBits_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "f5_system_throughputPerformance_outBits_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "SSL HANDSHAKE FAILURES",
   "type": "timeseries",
   "description": "This is the all-time total number of handshake failures, which is a running counter and will never be zero.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(f5_handshakeFailures{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_tmmcpu{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TMM MEMORY",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_tmmMemory{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "No. INTERFACES",
   "type": "stat",
   "description": "Number of network interfaces.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_name{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL HTTP STATUS CODES",
   "type": "stat",
   "description": "The total number of times each HTTP status code group has appeared.",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_2xxResp{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(f5_3xxResp{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(f5_4xxResp{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(f5_5xxResp{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "2m RESPONSE TIMES",
   "type": "text",
   "description": "The response times of each HTTP profile that was less than or greater than 2 minutes.",
   "gridPos": { "h": 2, "w": 6, "x": 7, "y": 56 },
   "options": {
    "content": "Number of response times of HTTP profiles."
   }
  },
  {
   "title": "INTERFACE MGMT",
   "type": "timeseries",
   "description": "Bits In/Out for MGMT interface.",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "f5_counters_bitsIn{job=\"$job\",instance=\"$instance\",networkInterfaces=\"mgmt\"}",
     "legendFormat": "{{networkInterfaces}} In"
    },
    {
     "expr": "f5_counters_bitsOut{job=\"$job\",instance=\"$instance\",networkInterfaces=\"mgmt\"}",
     "legendFormat": "{{networkInterfaces}} Out"
    }
   ]
  },
  {
   "title": "RESPONSE LESS THAN",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 58 },
   "targets": [
    {
     "expr": "f5_respLessThan2m{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{httpProfiles}}"
    }
   ]
  },
  {
   "title": "INTERFACE 1.0",
   "type": "timeseries",
   "description": "Bits In/Out for MGMT interface.",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "f5_counters_bitsIn{job=\"$job\",instance=\"$instance\",networkInterfaces=\"1.0\"}",
     "legendFormat": "{{networkInterfaces}} In"
    },
    {
     "expr": "f5_counters_bitsOut{job=\"$job\",instance=\"$instance\",networkInterfaces=\"1.0\"}",
     "legendFormat": "{{networkInterfaces}} Out"
    }
   ]
  },
  {
   "title": "Virtual Server Status",
   "type": "stat",
   "description": "Total: Number of virtual servers setup.\nEnabled: Number of virtual servers enabled.\nAvailable: Number of virtual servers functioning properly.",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_isEnabled{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(f5_isEnabled{job=\"$job\",instance=\"$instance\"} == 1)",
     "legendFormat": "Enabled"
    },
    {
     "expr": "sum(f5_isAvailable{job=\"$job\",instance=\"$instance\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "RESPONSE GREATER THAN",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 63 },
   "targets": [
    {
     "expr": "f5_respGreaterThan2m{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{httpProfiles}}"
    }
   ]
  },
  {
   "title": "CLIENT SIDE - VIRTUAL SERVER CURRENT CONNECTIONS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_clientside_curConns{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{virtualServers}}"
    }
   ]
  },
  {
   "title": "CLIENT SIDE - VIRTUAL SERVER BITS IN/OUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "f5_clientside_bitsIn{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{virtualServers}} In"
    },
    {
     "expr": "f5_clientside_bitsOut{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{virtualServers}} Out"
    }
   ]
  }
 ]
}